sudo: required
dist: trusty
language: csharp
solution: Opuz2015.sln
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y libcairo1.10-cil libgio3.0-cil libgdk3.0-cil libglib3.0-cil
install:
      - git submodule update --init --recursive
      - nuget restore Opuz2015.sln
script:
      - xbuild /p:Configuration=Release Opuz2015.sln

